### ISSUE TITLE
Any roadmap, plans on being easily forkable?

### ISSUE THREAD

**Issue by agustif** [cerclecrm/cercle#27]
I'm sorry if the title of my issue isn't clear enough.

What I mean by that, is 
Do you have any kind of public roadmap, be it in a blogpost or whatever? This project really fits my  needs, but not 100% obviously.

I want to build a CRM/Client/Seller/Proposals envirorment for my mum's travel agency.
Most of the work is done in cercle, but I need some custom domain that I'm probably guessing won't be relevant to core, since is a lot of business-logic related, like storing passengers related to every contact (in case of them, purchasing travel services for 1+, which in cruising, is usually always)

I need to also store some documents per passenger, probably saving a file until a review is done, (data extracted manually) like expedition/expiration dates, stored to database, and the original file deleted (for security reasons) I'm guessing storing indefinetly high resolution copies of personal documentation is a no-no from a security POV.

So I'm thinking what would be the best way to approach my attempt, Simply Fork, Rename, and go on from there. or maybe wait for modularity like being able to pull cercle as an --umbrella application, where I could also host other apps like an invoicing system, or a notifications app

Anyways, I never worked with vue either, and was wondering what was the reasoning behind the add, I find the UI a little buggy on OSX, Chrome, and wondered how hard it would be to implement in pure phoenix (Im guessing drag and drop and other features make the JS frontend route the best one for the project) Also I researched a little and for example the famous trello example uses react for the front, which doesn't solve my question of could we make this UI without a full-fledged JS frontend)

**Comment by antoineherzog** [comment]
hi @agustif 
thank you very much for your interest in Cercle!
We are planning to release the roadmap next week. I will send it to you next week! But already i can tell we will release the attachments feature in 1 or 2 weeks so you will be able to upload files on your cards related to your contacts.
Regarding custom attributes, i am going to write a guide to add your own fields, it is very easy, You just need to do a migration and add the field in the API and the Vuejs component.
I would be happy to help you with the fork. Maybe we can do a skype or something. So far we are 3 senior developper working on Cercle CRM for Trello lovers.
We choose Vuejs for 3 main reasons:
- much simpler than React or Angular. You can follow tutorial here. We love Vuejs much more than react. So Simple ! And also Phoenix + Vuejs is working very well together.
- We wanted to have a clear JS framework because we are realtime ready :)
- To be able to use millions of components so we don't reinvent the wheels.
Cheers,
Antoine

@harish86 @parallel588

**Comment by agustif** [comment]
Hi @antoineherzog 

Thank you for open sourcing, I like to follow along elixir projects and was really happy to found yours.

The attachment add is great news, I'm curious will you be using Arc for it? There's a new package which currently only works with AWS/SFTP/local FileSystem, which makes easy to manage multiple filesystem targets.

I'm really interested in working on this project, I do have some free time every day I could dedicate to this.

Anyways, I'm a bit noob, and mostly know only elixir and some JS, but I can code with the correct guidance on PR's

I  have read good stuff about Vue, so I can give it a try, and if I can get any help from one of you as in mentoring I'm sure I can crack it for my needs.

**Comment by antoineherzog** [comment]
Hi @agustif  

It sounds great! Welcome ! @parallel588 @harish86 

Yes Arc sounds good and we keep it simple. I think it is good choice, what do you think?

Yeah vuejs is killing it! It is going to be the next jQuery :)

I am going to add your account on our internal trello board for the Cercle TEAM.

Also we can plan a skype chat when you have times ?

on a side note, i will be in Barcelona in 2 weeks so maybe we can meet there also.

Have a good day :)

Antoine

**Comment by agustif** [comment]
Thanks @antoineherzog up and running on the trello!!

Nice man, I'm on mexico but have plans to be in Girona/Barcleona in one or two weeks, let me know when you're in barcelona and we should meet!

**Comment by antoineherzog** [comment]
sounds good @agustif i will let you know so we can meet in Barcelona !!
